# Copyright (c) 2018, 2020, Oracle Corporation and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

# Default values for ingress-per-domain.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Load balancer type.  Supported values are: NGINX, TRAEFIK, VOYAGER
type: NGINX

# WLS domain as backend to the load balancer
wlsDomain:
  domainUID: domain1
  clusterName: cluster-1
  managedServerPort: 8001

# Nginx specific values
nginx:
  hostname: domain1.org

# Traefik specific values
traefik:
  # hostname used by host-routing
  hostname: domain1.org

# Voyager specific values
voyager:
  # web port
  webPort: 30305
  # stats port
  statsPort: 30315
